using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using SMP.EPL;
using SMP.BL;

namespace SMP.PL
{
    public partial class frm_Category : Form
    {
        Methods methods = new Methods();
        DB_SMPEntities db =new DB_SMPEntities();
        Category tb_cat = new Category();
        
        int id;
        public frm_Category()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SMP.DB_SMPEntities dbContext = new SMP.DB_SMPEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Categories.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.Categories.Local.ToBindingList();

        }

        private void btn_Add_Click(object sender, EventArgs e)
        {
            frm_CategoryADD frm_add = new frm_CategoryADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "Add";
            frm_add.Show();
            update_data();

        }

        private void btn_Update_Click(object sender, EventArgs e)
        {
            update_data();
        }

        private void btn_Delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();

            try
            {
                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
                var rs = MessageBox.Show( "are you sure to delete the category ?", "Delete Proccess", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {
                    tb_cat = db.Categories.Where(x => x.ID == id).FirstOrDefault();
                    db.Entry(tb_cat).State = EntityState.Deleted;
                    db.SaveChanges();
                    toast.lbl_Caption.Text = "The Category has been deleted";
                    toast.Width = this.Width;
                    toast.Show();
                    update_data();
                }

            }
            catch {

                dialog.lbl_Caption.Text = "There is no category to delete";
                dialog.Width = this.Width;
                dialog.Show();
            
            
            }
            

            
        }
            public void update_data()
        {
            db = new DB_SMPEntities();
            gridControl1.DataSource = db.Categories.ToList();
        }

        private void btn_Edit_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();

            try
            {
                frm_CategoryADD frm_add = new frm_CategoryADD();
                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
                tb_cat = db.Categories.Where(x => x.ID == id).FirstOrDefault();
                frm_add.txt_EditName.Text = tb_cat.CAT_Name.ToString();
                methods.by = tb_cat.Cat_Cover;
                frm_add.pic_cover.Image = Image.FromStream(methods.convert_image());
                frm_add.id = id;
                frm_add.btn_add.Text = "Edit";
                frm_add.Show();
                update_data();
            }
            catch
            {
                dialog.lbl_Caption.Text = "There is no category to Edit";
                dialog.Width = this.Width;
                dialog.Show();
            }
        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search=txt_search.Text;
            gridControl1.DataSource=db.Categories.Where(x=>x.CAT_Name.Contains(_search)).ToList();
        }
    }
}
